[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore documentation
    '''README.md''',

    # Ignore tests
    '''tests\/.*\.phpt''',
  ]


